name: ecog_py
dependencies:
  - numpy
  - sympy
  - matplotlib
  - pandas
  - scipy
  - pip
  - h5py
  - ipython
  - nose
  - scikit-learn
  - mkl_fft
  - jupyter
  - sphinx
  - pip:
    - process-nwb
    - pynwb
